// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using schliessanlagen_konfigurator.Data;

#nullable disable

namespace schliessanlagenkonfigurator.Migrations
{
    [DbContext(typeof(schliessanlagen_konfiguratorContext))]
    [Migration("20240215155118_Order")]
    partial class Order
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Aussenzylinder_Rundzylinder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artikelnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("schliessanlagenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("schliessanlagenId");

                    b.ToTable("Aussenzylinder_Rundzylinder");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Hebelzylinder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artikelnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("schliessanlagenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("schliessanlagenId");

                    b.ToTable("Hebelzylinder");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Options", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Aussenzylinder_RundzylinderId")
                        .HasColumnType("int");

                    b.Property<string>("Bohrschutz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bügelhöhe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Freilauf")
                        .HasColumnType("bit");

                    b.Property<int?>("HebelzylinderId")
                        .HasColumnType("int");

                    b.Property<int?>("IdAussenzylinder_Rundzylinder")
                        .HasColumnType("int");

                    b.Property<int?>("IdHebelzylinder")
                        .HasColumnType("int");

                    b.Property<int?>("IdProfil_Doppelzylinder")
                        .HasColumnType("int");

                    b.Property<int?>("IdProfil_Halbzylinder")
                        .HasColumnType("int");

                    b.Property<int?>("IdProfil_Knaufzylinder")
                        .HasColumnType("int");

                    b.Property<int?>("IdVorhangschloss")
                        .HasColumnType("int");

                    b.Property<string>("Modulbauweise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NG_Funktion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Profil_DoppelzylinderId")
                        .HasColumnType("int");

                    b.Property<int?>("Profil_HalbzylinderId")
                        .HasColumnType("int");

                    b.Property<int?>("Profil_KnaufzylinderId")
                        .HasColumnType("int");

                    b.Property<string>("Schließbart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Schließhebel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Schließweg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VorhangschlossId")
                        .HasColumnType("int");

                    b.Property<string>("Witterungsschutz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zubehör")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zylinderfärbung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zylinderknauf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Aussenzylinder_RundzylinderId");

                    b.HasIndex("HebelzylinderId");

                    b.HasIndex("Profil_DoppelzylinderId");

                    b.HasIndex("Profil_HalbzylinderId");

                    b.HasIndex("Profil_KnaufzylinderId");

                    b.HasIndex("VorhangschlossId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Orders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("CountKey")
                        .HasColumnType("int");

                    b.Property<bool?>("IsOppen")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen10")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen11")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen12")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen13")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen14")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen15")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen16")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen17")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen18")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen19")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen2")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen20")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen3")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen4")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen5")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen6")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen7")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen8")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOppen9")
                        .HasColumnType("bit");

                    b.Property<string>("NameKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZylinderId")
                        .HasColumnType("int");

                    b.Property<float?>("aussen")
                        .HasColumnType("real");

                    b.Property<float?>("innen")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Profil_Doppelzylinder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artikelnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<double>("Extern")
                        .HasColumnType("float");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Intern")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("max")
                        .HasColumnType("float");

                    b.Property<double>("min")
                        .HasColumnType("float");

                    b.Property<int>("schliessanlagenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("schliessanlagenId");

                    b.ToTable("Profil_Doppelzylinder");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Profil_Halbzylinder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artikelnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Außen")
                        .HasColumnType("float");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("max")
                        .HasColumnType("float");

                    b.Property<double>("min")
                        .HasColumnType("float");

                    b.Property<int>("schliessanlagenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("schliessanlagenId");

                    b.ToTable("Profil_Halbzylinder");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Profil_Knaufzylinder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artikelnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<double>("Extern")
                        .HasColumnType("float");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Intern")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("max")
                        .HasColumnType("float");

                    b.Property<double>("min")
                        .HasColumnType("float");

                    b.Property<int>("schliessanlagenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("schliessanlagenId");

                    b.ToTable("Profil_Knaufzylinder");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Schliessanlagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("nameType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schliessanlagen");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Vorhangschloss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artikelnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("schliessanlagenId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Сost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("schliessanlagenId");

                    b.ToTable("Vorhangschloss");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Aussenzylinder_Rundzylinder", b =>
                {
                    b.HasOne("schliessanlagen_konfigurator.Models.Schliessanlagen", "Schliessanlagen")
                        .WithMany("Aussenzylinder_Rundzylinder")
                        .HasForeignKey("schliessanlagenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schliessanlagen");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Hebelzylinder", b =>
                {
                    b.HasOne("schliessanlagen_konfigurator.Models.Schliessanlagen", "Schliessanlagen")
                        .WithMany("Hebelzylinder")
                        .HasForeignKey("schliessanlagenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schliessanlagen");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Options", b =>
                {
                    b.HasOne("schliessanlagen_konfigurator.Models.Aussenzylinder_Rundzylinder", null)
                        .WithMany("Options")
                        .HasForeignKey("Aussenzylinder_RundzylinderId");

                    b.HasOne("schliessanlagen_konfigurator.Models.Hebelzylinder", null)
                        .WithMany("Options")
                        .HasForeignKey("HebelzylinderId");

                    b.HasOne("schliessanlagen_konfigurator.Models.Profil_Doppelzylinder", null)
                        .WithMany("Options")
                        .HasForeignKey("Profil_DoppelzylinderId");

                    b.HasOne("schliessanlagen_konfigurator.Models.Profil_Halbzylinder", null)
                        .WithMany("Options")
                        .HasForeignKey("Profil_HalbzylinderId");

                    b.HasOne("schliessanlagen_konfigurator.Models.Profil_Knaufzylinder", null)
                        .WithMany("Options")
                        .HasForeignKey("Profil_KnaufzylinderId");

                    b.HasOne("schliessanlagen_konfigurator.Models.Vorhangschloss", null)
                        .WithMany("Options")
                        .HasForeignKey("VorhangschlossId");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Profil_Doppelzylinder", b =>
                {
                    b.HasOne("schliessanlagen_konfigurator.Models.Schliessanlagen", "Schliessanlagen")
                        .WithMany("Profil_Doppelzylinder")
                        .HasForeignKey("schliessanlagenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schliessanlagen");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Profil_Halbzylinder", b =>
                {
                    b.HasOne("schliessanlagen_konfigurator.Models.Schliessanlagen", "Schliessanlagen")
                        .WithMany("Profil_Halbzylinder")
                        .HasForeignKey("schliessanlagenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schliessanlagen");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Profil_Knaufzylinder", b =>
                {
                    b.HasOne("schliessanlagen_konfigurator.Models.Schliessanlagen", "Schliessanlagen")
                        .WithMany("Profil_Knaufzylinder")
                        .HasForeignKey("schliessanlagenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schliessanlagen");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Vorhangschloss", b =>
                {
                    b.HasOne("schliessanlagen_konfigurator.Models.Schliessanlagen", "Schliessanlagen")
                        .WithMany("Vorhangschloss")
                        .HasForeignKey("schliessanlagenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schliessanlagen");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Aussenzylinder_Rundzylinder", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Hebelzylinder", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Profil_Doppelzylinder", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Profil_Halbzylinder", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Profil_Knaufzylinder", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Schliessanlagen", b =>
                {
                    b.Navigation("Aussenzylinder_Rundzylinder");

                    b.Navigation("Hebelzylinder");

                    b.Navigation("Profil_Doppelzylinder");

                    b.Navigation("Profil_Halbzylinder");

                    b.Navigation("Profil_Knaufzylinder");

                    b.Navigation("Vorhangschloss");
                });

            modelBuilder.Entity("schliessanlagen_konfigurator.Models.Vorhangschloss", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
